services:
  - type: web
    name: spn-backend
    root: backend
    dockerfilePath: Dockerfile
    envVars:
      - key: MONGO_URI
        value: mongodb://localhost:27017/spn_db
      - key: NODE_ENV
        value: production
